// src/services/database.service.ts
import { Injectable, InternalServerErrorException, Logger } from '@nestjs/common';
const hana = require('@sap/hana-client');

@Injectable()
export class DatabaseService {
  private readonly logger = new Logger(DatabaseService.name);
  private client: any;

  constructor() {
    const connParams = {
      serverNode: 'd76aa042-8df4-48ff-8373-c4d8f74588d4.hana.trial-us10.hanacloud.ondemand.com:443',
      uid: 'DBADMIN',
      pwd: 'invent2K25',
    };

    this.client = hana.createClient(connParams);

    this.client.connect((err: any) => {
      if (err) {
        this.logger.error('Connection failed', err);
      } else {
        this.logger.log('Connected to the database');
        //remove this line if db created once 

       // this.initializeDatabase(); // Initialize the database (create tables if they don't exist)
      }
    });
  }

  // Initialize the database (create tables if they don't exist)
  private async initializeDatabase(): Promise<void> {
    try {
      // Check if the ForexAlerts table exists
      const tableExists = await this.executeQuery(
        `SELECT COUNT(*) AS TABLE_EXISTS FROM TABLES WHERE TABLE_NAME = 'ForexAlerts' AND SCHEMA_NAME = CURRENT_SCHEMA`,
      );

      if (tableExists[0].TABLE_EXISTS === 0) {
        // Create the ForexAlerts table
        await this.executeQuery(`
          CREATE TABLE ForexAlerts (
            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            userId VARCHAR(255) NOT NULL,
            type VARCHAR(50) NOT NULL, -- 'forex' or 'interest'
            baseCurrency VARCHAR(10), -- Only for forex alerts
            targetCurrency VARCHAR(10), -- Only for forex alerts
            foreignCurrency VARCHAR(10), -- Only for interest alerts
            lowThreshold DECIMAL(10, 4) NOT NULL,
            highThreshold DECIMAL(10, 4) NOT NULL,
            createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          )
        `);
        this.logger.log('ForexAlerts table created successfully');
      } else {
        this.logger.log('ForexAlerts table already exists');
      }
    } catch (error) {
      this.logger.error('Failed to initialize database', error);
      throw new InternalServerErrorException('Failed to initialize database');
    }
  }

  // Insert or update a forex alert
  async upsertForexAlert(alertData: {
    userId: string;
    baseCurrency: string;
    targetCurrency: string;
    lowThreshold: number;
    highThreshold: number;
  }): Promise<void> {
    const { userId, baseCurrency, targetCurrency, lowThreshold, highThreshold } = alertData;

    // Check if an alert already exists for the same user and currency pair
    const existingAlert = await this.executeQuery(
      `SELECT * FROM ForexAlerts WHERE userId = ? AND baseCurrency = ? AND targetCurrency = ? AND type = 'forex'`,
      [userId, baseCurrency, targetCurrency],
    );

    if (existingAlert.length > 0) {
      // Update the existing alert
      await this.executeQuery(
        `UPDATE ForexAlerts SET lowThreshold = ?, highThreshold = ? WHERE USERID = ?`,
        [lowThreshold, highThreshold, existingAlert[0].USERID],
      );
      this.logger.log('Forex alert updated successfully');
    } else {
      // Insert a new alert
      await this.executeQuery(
        `INSERT INTO ForexAlerts (userId, type, baseCurrency, targetCurrency, lowThreshold, highThreshold)
         VALUES (?, 'forex', ?, ?, ?, ?)`,
        [userId, baseCurrency, targetCurrency, lowThreshold, highThreshold],
      );
      this.logger.log('Forex alert inserted successfully');
    }
  }

  // Insert or update an interest rate alert
  async upsertInterestRateAlert(alertData: {
    userId: string;
    foreignCurrency: string;
    lowThreshold: number;
    highThreshold: number;
  }): Promise<void> {
    const { userId, foreignCurrency, lowThreshold, highThreshold } = alertData;

    // Check if an alert already exists for the same user and foreign currency
    const existingAlert = await this.executeQuery(
      `SELECT * FROM ForexAlerts WHERE userId = ? AND foreignCurrency = ? AND type = 'interest'`,
      [userId, foreignCurrency],
    );

    if (existingAlert.length > 0) {
      // Update the existing alert
      await this.executeQuery(
        `UPDATE ForexAlerts SET lowThreshold = ?, highThreshold = ? WHERE id = ?`,
        [lowThreshold, highThreshold, existingAlert[0].id],
      );
      this.logger.log('Interest rate alert updated successfully');
    } else {
      // Insert a new alert
      await this.executeQuery(
        `INSERT INTO ForexAlerts (userId, type, foreignCurrency, lowThreshold, highThreshold)
         VALUES (?, 'interest', ?, ?, ?)`,
        [userId, foreignCurrency, lowThreshold, highThreshold],
      );
      this.logger.log('Interest rate alert inserted successfully');
    }
  }

  // Fetch all forex alerts
  async getAllForexAlerts(): Promise<any[]> {
    const query = "SELECT * FROM ForexAlerts WHERE type = 'forex'";
    try {
      const alerts = await this.executeQuery(query);
      return alerts;
    } catch (error) {
      this.logger.error('Failed to fetch forex alerts', error);
      throw new InternalServerErrorException('Failed to fetch forex alerts');
    }
  }

  // Fetch all interest rate alerts
  async getAllInterestRateAlerts(): Promise<any[]> {
    const query = "SELECT * FROM ForexAlerts WHERE type = 'interest'";
    try {
      const alerts = await this.executeQuery(query);
      return alerts;
    } catch (error) {
      this.logger.error('Failed to fetch interest rate alerts', error);
      throw new InternalServerErrorException('Failed to fetch interest rate alerts');
    }
  }

  // Helper method to execute queries
  private async executeQuery(query: string, params: any[] = []): Promise<any[]> {
    return new Promise((resolve, reject) => {
      this.client.exec(query, params, (err: any, rows: any[]) => {
        if (err) {
          this.logger.error('Failed to execute query', err);
          return reject(err);
        }
        resolve(rows);
      });
    });
  }

 // Fetch the latest forex rate for a specific currency pair
 async getLatestForexRate(baseCurrency: string, targetCurrency: string): Promise<number> {
    try {
      const query = `
        SELECT Exchange_Rate FROM forex
        WHERE base_Currency = ? AND target_Currency = ?
        ORDER BY timestamp DESC
        LIMIT 1
      `;
    //   console.log(query);
      const result = await this.executeQuery(query, [baseCurrency, targetCurrency]);

      console.log(`The result from the forex table:${result[0].EXCHANGE_RATE}`);
      if (result.length === 0) {
        throw new Error(`No forex rate found for ${baseCurrency}/${targetCurrency}`);
      }

      const rate = result[0].EXCHANGE_RATE;
      this.logger.log(`Fetched forex rate for ${baseCurrency}/${targetCurrency}: ${rate}`);
      return rate;
    } catch (error) {
      this.logger.error('Failed to fetch forex rate', error);
      throw new InternalServerErrorException('Failed to fetch forex rate');
    }
  }

  private async fetchInterestRate(): Promise<number> {
    try {
      // Fetch the latest interest rate from the database
      const query = `
        SELECT rate FROM interest
        WHERE currency = ?
        ORDER BY timestamp DESC
        LIMIT 1
      `;
      const result = await this.executeQuery(query, ['USD']); // Replace with your currency
  
      if (result.length === 0) {
        throw new Error('No interest rate found in the database');
      }
  
      const rate = result[0].rate;
      this.logger.log(`Fetched interest rate from database: ${rate}`);
      return rate;
    } catch (error) {
      this.logger.error('Failed to fetch interest rate from database', error);
      throw error;
    }
  }


  // src/services/database.service.ts
// async insertNotification(notificationData: {
//     userId: string;
//     type: string;
//     message: string;
//   }): Promise<void> {
//     const insertSQL = `
//       INSERT INTO notifications (userId, type, message)
//       VALUES (?, ?, ?)
//     `;
  
//     try {
//       await this.executeQuery(insertSQL, [
//         notificationData.userId,
//         notificationData.type,
//         notificationData.message,
//       ]);
//       this.logger.log('Notification inserted successfully');
//     } catch (error) {
//       this.logger.error('Failed to insert notification', error);
//       throw new InternalServerErrorException('Failed to insert notification');
//     }
//   }
  
  async getNotificationsByUser(userId: string): Promise<any[]> {
    const query = 'SELECT * FROM notifications WHERE userId = ? ORDER BY createdAt DESC';
    try {
      const notifications = await this.executeQuery(query, [userId]);
      return notifications;
    } catch (error) {
      this.logger.error('Failed to fetch notifications', error);
      throw new InternalServerErrorException('Failed to fetch notifications');
    }
  }

  
}